main: com.ttakkku.brotherharass.Main
version: 1.0
author: ttakkku
load: STARTUP
api-version: 1.0
database: false
name: Discordbot
commands:
  hello:
    aliases:
      - ㅎㅇ
    description: 이건 명령어 테스트입니다
    usage: /hello